var msgMap = {
	"dim.label.dimName":{zh:"维度名称",en:"Name"},
	"dim.label.createType":{zh:"创建方式",en:"Type"},
	"dim.label.createType.text":{zh:"文本编辑",en:"Text"},
	"dim.label.createType.import":{zh:"已有数据导入",en:"Import"},
	"dim.label.createType.sql":{zh:"SQL配置",en:"Sql"},
	"dim.label.parentDimName":{zh:"上级维度",en:"Superior"},
	"dim.label.count":{zh:"维度记录条数",en:"Count"},
	"dim.label.desc":{zh:"维度描述",en:"Description"},
	"dim.label.createTime":{zh:"创建时间",en:"Create Time"},
	"dim.label.opt":{zh:"操作",en:"Operate"},
	"dim.label.dimCode":{zh:"维度值",en:"Code"},
	"dim.label.dimLabel":{zh:"维度名称",en:"Label"},
	"dim.label.parentCode":{zh:"上级维度值",en:"Superior Code"},
	
	"dim.buttom.opt.update":{zh:"修改",en:"Update"},
	"dim.buttom.opt.delete":{zh:"删除",en:"Delete"},
	
	"dim.title.confirm":{zh:"确认",en:"Confirm"},
	"dim.title.tips":{zh:"提示",en:"Tips"},
	"dim.title.succeed":{zh:"成功",en:"Succeed"},
	"dim.title.error":{zh:"错误",en:"Error"},
	
	"dim.message.loading":{zh:"正在加载数据，请稍后",en:"Loading data, please wait"},
	"dim.message.opt.confirm":{zh:"您确定要保存该维度信息吗？",en:"Are you sure you want to save this dimension?"},
	"dim.message.opt.doing":{zh:"正在保存维度信息，请稍后...",en:"Saving dimension information, please later."},
	"dim.message.opt.succeed":{zh:"保存维度信息成功！",en:"Save dimension information successfully! "},
	"dim.message.opt.error":{zh:"保存维度信息失败！",en:"Save dimension information failure! "},
	"dim.message.delete.confirm":{zh:"您确定要删除该维度信息吗？删除后该维度关联的权限控制信息也将被删除。",en:"Are you sure you want to delete this dimension?"},
	"dim.message.delete.doing":{zh:"正在删除维度信息，请稍后...",en:"Removing dimension information, please later."},
	"dim.message.delete.succeed":{zh:"删除维度信息成功！",en:"Delete dimension information successfully!"},
	"dim.message.delete.error":{zh:"删除维度信息失败！",en:"Delete dimension information failure! "},
	"dim.message.delete.disable":{zh:"无法删除维度信息，关联了数据{1}",en:"Unable to delete dim info, associated data{1}"},
	"dim.message.noRecord":{zh:"没有符合条件的查询结果！",en:"No query results are in accord with the condition!"},
	"dim.message.query.dimInfo.error":{zh:"初始化维度基本信息失败！",en:"Initialization dimension basic information failure!"},
	"dim.message.query.dimData.error":{zh:"初始化维度数据信息失败！",en:"Failed to initialize dimension data!"},
	"dim.message.query.data.error":{zh:"加载数据源数据失败！",en:"Failed to load data source!"},
	"dim.message.query.result.error":{zh:"生成维度结果数据失败！",en:"Generating dimension result data failure!"},
	"dim.message.check.error":{zh:"校验维度结果时发生错误！",en:"Error checking dimension results!"}
}
