var msgMap = {
		"user.label.uploadSucceed": {zh: "上传成功", en: "upload successfully"},
		"user.label.pleaseSelectSex": {zh: "请选择用户性别", en: "Select user gender"},
		"user.label.confirm": {zh: "确认", en: "confirm"},
		"user.label.confirmSave": {zh: "您确定要更改用户信息吗？", en: "are you sure to save?"},
		"user.label.confirmPreserve": {zh: "您确定要保存用户信息吗？", en: "are you sure to Preserve?"},
		"user.label.tip": {zh: "提示", en: "upload successfully"},
		"user.label.pleaseWait": {zh: "正在保存用户信息，请稍后", en: "upload successfully"},
		"user.label.succeed": {zh: "成功", en: "upload successfully"},
		"user.label.error": {zh: "错误", en: "upload successfully"},
		"user.label.saveSuccesfully": {zh: "用户信息保存成功！", en: "upload successfully"},
		"user.label.saveFail": {zh: "用户信息保存失败", en: "upload successfully"},
		"user.label.saveError": {zh: "用户信息保存过程中出现异常", en: "upload successfully"},
		"user.label.del.confirm": {zh: "您确定要删除该用户的信息吗？", en: "Are you sure you want to delete the user's information?"},
		"user.label.del.loading": {zh: "正在删除用户信息，请稍后...", en: "Deleting user information, please wait..."},
		"user.label.delError": {zh: "删除用户信息过程中出现异常！", en: "Delete user information in the process of abnorma!"},
		"user.label.timeout":{zh:"获取ip对应地址超时",en:"link timeout"},
		"user.label.unbindMobile":{zh:"请先绑定手机",en:"Please bind the mobile"},	
		"user.userlist.label.signature": {zh: "贵公司人数已达上限，无法添加员工，请到<a class='orderusernum'>企业用户数扩容</a>页面调整！",en: "The number of your company has reached the upper limit, can not add staff,Please go to the<a class='orderusernum'>Enterprise user number expansion</a>adjustment"},
		"user.userlist.button.add": {zh: "编辑用户", en: "Edit user"},
		"user.userlist.button.save": {zh: "保存", en: "Save"},
		"user.userlist.button.cancel": {zh: "取消", en: "Cancel"},
		"user.userlist.label.userId": {zh: "用户编码", en: "UserId"},
		"user.userlist.label.userName": {zh: "用户名称", en: "UserName"},
		"user.userlist.label.job": {zh: "角色名称", en: "Job"},
		"user.userlist.label.sex": {zh: "性别", en: "Sex"},
		"user.userlist.label.dept": {zh: "部门", en: "Department"},
		"user.userlist.label.email": {zh: "邮箱", en: "Email"},
		"user.userlist.label.phone": {zh: "手机号", en: "Phone"},
		"user.userlist.label.operation": {zh: "操作", en: "Operation"},
		"user.userlist.label.del": {zh: "删除", en: "Delete"},
		"user.userlist.label.modify": {zh: "修改", en: "Modify"}

};
