var msgMap = {
	"home.label.TipBox": {zh: "提示框", en: "Tip box"},
    "home.msg.repeatMsg": {zh: "您已选择该报表，不可重复选择!", en: "You have chosen this report, you can not choose!"},
    "home.button.sure": {zh: "确定", en: "&nbsp;Sure&nbsp;"},
    "home.button.cancel": {zh: "取消", en: "Cancel"},
    "home.label.confirmBox": {zh: "确认框", en: "confirm box"},
    "home.msg.mostMsg": {zh: "首页分析报表最多选择5条，确定将覆盖最后一条，是否继续？", en: "Home analysis report up to 5, determine whether the last one, whether to continue?"},
    "home.msg.deleteMsg": {zh: "请勾选需要删除的报表！", en: "Please check the report that you need to delete!"},
    "home.msg.deleteConfirmMsg": {zh: "确定删除勾选的报表吗？", en: "Determines the report for the deletion of the check?"},
    "home.page.first": {zh: "首页", en: "First"},
    "home.page.last": {zh: "尾页", en: "Last"},
    "home.page.jump": {zh: "跳转", en: "Jump"},
    "home.msg.sethome1": {zh: "您确定设置这", en: "Are you sure you set up the  "},
    "home.msg.sethome2": {zh: "张报表为首页吗", en: " reports for the home page?"},
    "home.msg.sethome3": {zh: "您确定为选中员工设置这", en: "Are you sure you set up the  "},
    "home.msg.execution": {zh: "执行中...", en: "Execution..."},
    "home.msg.submitMsg": {zh: "正在提交信息，请稍后", en: "Is submitting information, please later"},
    "home.msg.successSet": {zh: "您已成功设置首页报表!", en: "You have successfully set the home page report!"},
    "home.label.comment": {zh: "点评", en: "Comment"},
    "home.label.visit": {zh: "访问量", en: "PV"},
    "report.label.more": {zh: "更多", en: "More"},
    "report.label.back": {zh: "收起", en: "Back"},
    "report.label.noReport1": {zh: "抱歉！没有找到与",en: "I'm sorry Associated with the"},
    "report.label.noReport2": {zh: "相关的报表。",en: " did not find the report."},
    "report.label.noReport3": {zh: "您还没有相关报表，请点击制作报表按钮制作报表！",en: "You do not have the relevant statements, please click on the production report button making reports!"},
    "report.label.noReportLabel": {zh: "标签：",en: "label:"},
    "report.label.noReportTxt": {zh: "搜索内容：",en: "search content:"},
    "report.label.noReportAnd": {zh: "且为",en: "and"},
    "report.button.homeset":{zh: "设为首页", en: "Set home"},
    "report.button.focus":{zh: "关&nbsp;&nbsp;注", en: "Focus this"},
    "report.button.unfocus":{zh: "取消关注", en: "unFocus"},
    "report.button.edit":{zh: "修改", en: "Edit"},
    "report.button.delete":{zh: "删除", en: "Delete"},
    "report.button.deleteing":{zh: "正在删除中", en: "Being deleted"},
    "report.button.deleteSuccess":{zh: "删除成功！", en: "Delete success!"},
    "report.button.share":{zh: "发布", en: "Share"},
    "report.msg.delete":{zh: "您确定删除该报表吗？", en: "Are you sure you want to delete this report?"},
    "report.share.title":{zh: "报表分享", en: "Report sharing"},
    "report.publish.title":{zh: "应用发布", en: "Publish report to the third party"},
    "report.share.userName":{zh: "用户名称", en: "User name"},
    "report.share.check":{zh: "请选择人员!", en: "Select  persons!"},
    "report.share.select":{zh: "请选择分享路径!", en: "Please choose to share the path!"},
    "report.share.successShare":{zh: "分享成功!", en: "Share success!"},
    "report.share.noCompanyMsg":{zh: "非企业用户无法分享报表！", en: "非企业用户无法分享报表！"},
    "msg.button.open":{zh: "开启全选", en: "Select Open"},
    "msg.button.close":{zh: "关闭全选", en: "Select Close"},
    "msg.label.deleteTip":{zh: "请勾选需要删除的消息！", en: "Please check the messages you need to delete!"},
    "msg.label.deleteMsg":{zh: "您确认删除选择的消息吗？", en: "Are you sure you delete the selected message?"},
    "msg.label.sender":{zh: "消息发送人：", en: "Message sender："},
    "msg.label.all":{zh: "全部", en: "All"},
    "msg.label.new":{zh: "新消息", en: "New news"},
    "msg.label.ordinary":{zh: "一般", en: "Ordinary"},
    "msg.label.important":{zh: "重要", en: "Important"},
    "msg.label.urgent":{zh: "紧急", en: "Urgent"},
    "report.tpl.tipTitle":{zh: "提示", en: "tip"},
    "msg.tpl.queryTipFail":{zh: "可视化模板查询失败！", en: "Report template query failed!"},
    "msg.tpl.queryTipError":{zh: "可视化模板查询异常！", en: "Report template query exception!"},
    "report.tpl.noTip":{zh: "您还没有可视化模板,请到报表制作中创建可视化模板！", en: "You do not have a report template, create a report template to create a report!"},
    "report.tpl.queryBySingle":{zh: "单图", en: "Query type: single image"},
    "report.tpl.queryByMuch":{zh: "多图", en: "Query type: much image"},
    "report.tpl.queryByLatest":{zh: "最新", en: "Query type: latest"},
    "report.tpl.and":{zh: ",且为", en: ",and"},
    "report.tpl.queryContent":{zh: "搜索内容为:", en: "Search content for:"},
    "report.tpl.notFind":{zh: "抱歉！没有找到与", en: "Sorry！ Not find with"},
    "report.tpl.relatedTpl":{zh: "相关的可视化模板。", en: "related report templates."},
    "report.tpl.SingleType":{zh: "单图", en: "single image"},
    "report.tpl.muchType":{zh: "多图", en: "much image"},
    "report.tpl.type":{zh: "类型", en: "Type"},
    "report.tpl.useAmount":{zh: "使用量", en: "Use Amount"},
    "report.tpl.second":{zh: "次", en: "Second"},
    "report.tpl.del":{zh: "删除", en: "Delete"},
    "report.tpl.quote":{zh: "引用", en: "Quote"},
    "report.tpl.share":{zh: "分享", en: "Share"},
    "report.tpl.first":{zh: "首页", en: "First"},
    "report.tpl.last":{zh: "尾页", en: "Last"},
    "report.tpl.jump":{zh: "跳转", en: "Jump"},
    "msg.tpl.confirmDelTpl":{zh: "您确定需要删除该可视化模板吗？", en: "Are you sure you need to delete the report template?"},
    "report.tpl.executing":{zh: "执行中", en: "executing"},
    "report.tpl.delWait":{zh: "正在删除可视化模板,请稍候......", en: "Please wait while the report template is removed......"},
    "report.tpl.delSuccess":{zh: "删除可视化模板成功！", en: "Delete report template successfully!"},
    "report.tpl.delFail":{zh: "删除可视化模板失败！", en: "Failed to Delete report template!"},
    "report.tpl.delError":{zh: "删除可视化模板异常！", en: "Delete report template exceptions!"},
    "report.tpl.canNotShare":{zh: "非企业用户不可分享可视化模板！", en: "Non enterprise users can not share the report template!"},
    "report.tpl.canNotQuote":{zh: "单图可视化模板不可引用！", en: "Single chart report template can not be quoted!"},
    "report.tpl.userSelect":{zh: "用户选择", en: "User Select"},
    "report.tpl.sure":{zh: "确定", en: "Sure"},
    "report.tpl.cancel":{zh: "取消", en: "Cancel"},
    "report.reportlist.label.reportName":{zh: "仪表板名称", en: "report name"},
    "report.reportlist.label.createUsername":{zh: "制作人", en: "producer"},
    "report.reportlist.label.expireDate":{zh: "有效期", en: "Term of validity"},
    "report.reportlist.label.createTime":{zh: "发布时间", en: "Release time"},
    "report.reportlist.label.expireDateEdit":{zh: "有效期修改", en: "Validity modification"},
    "report.reportlist.button.cancel": {zh: "取消", en: "Cancel"},
    "report.reportlist.button.save": {zh: "保存", en: "Save"},
    "report.reportlist.msg.confirm": {zh: "确定", en: "Comfirm"},
    "report.reportlist.msg.saveConfirm": {zh: "你确定要保存报表有效期？", en: "Are you sure you need to save the term of validity?"},
    "report.reportlist.label.tip": {zh: "提示", en: "Tip"},
    "report.navi.get.error": {zh: "导航获取失败。", en: "Navi get error!"},
    
    
    "report.msg.save.exception": {zh: "保存报表有效期时出现异常！", en: "Abnormal when the term of validity is saved!"},
    "report.reportlist.label.pleaseWait": {zh: "正在处理请求，请稍后....", en: "Is processing your request, please wait for a monment..."},
    "data.user.title.selectSave":{zh:"用户选择保存",en:"User select save"},
	"data.user.message.confirmSave":{zh:"您确定需要保存吗？",en:"Are you sure you need to save it?"},
    "data.user.caption.power":{zh:"已赋权的用户",en:"Empowered user"},
	"data.user.caption.notPower":{zh:"未赋权的用户",en:"Not empowering users"},
	"data.user.label.userID":{zh:"用户编码",en:"User Code"},
	"data.user.label.userName":{zh:"用户名称",en:"User name"},
	"data.user.label.depName":{zh:"部门",en:"department"},
	"data.user.message.selectNotPower":{zh:"请在左侧选择未赋权的用户！",en:"Please select an option not to empower the user on the left!"},
	"data.user.message.selectPower":{zh:"请在右侧选择已赋权的用户！",en:"Please select the right user on the right!"},
	"data.user.loading.submit":{zh:"正在提交信息，请稍后.....",en:"Submitting information, please..."},
	"data.user.label.sure":{zh:"确定",en:"Sure"},
	"data.user.message.setFailed":{zh:"用户设置失败！",en:"User settings failed!"},
	"data.user.message.setError":{zh:"用户设置出错，保存失败！",en:"User set error, save failed!"},
	"data.user.message.setSuccess":{zh:"用户设置成功!",en:"User set successfully!"},
	"data.db.title.tips":{zh:"提示",en:"Tips"},
	"data.db.title.execute":{zh:"执行中",en:"Execute in"},
}
