var msgMap = {
	"safety.label.send.msg": {zh: "秒后，重新获取验证码", en: "seconds,recover message!"},
	"safety.button.getMsg": {zh: "重新获取验证码", en: "Recover message!"},
	
	"safety.msg.prompt": {zh: "提示", en: "Prompt"},
	"safety.msg.error": {zh: "错误", en: "Exception"},
	"safety.msg.loading": {zh: "正在处理请求...", en: "Processing request..."},
	"safety.msg.success": {zh: "成功", en: "Success"},
	"safety.msg.captcha.error": {zh: "图片校验码不正确！", en: "Captcha is four characters!"},
	"safety.msg.checkCode.error": {zh: "短信校验码不正确！", en: "SMS verification code is error!"},
	"safety.msg.checkCode.lengthError": {zh: "短信校验码为四位数字！", en: "SMS verification code is four numbers!"},
	"safety.msg.checkCode.expire": {zh: "短信校验码已失效，请重新验证！", en: "SMS verification code has failed, please re verify!"},
	"safety.msg.oldPsd.empty": {zh: "请输入旧密码！", en: "Please enter the old password!"},
	"safety.msg.newPsd.empty": {zh: "请输入新密码！", en: "Please enter the new password!"},
	"safety.msg.reNewPsd.empty": {zh: "请再次输入新密码！", en: "Please enter the renew password!"},
	"safety.msg.password.diff": {zh: "两次输入的密码不同！", en: "The password you enter are different"},
	"safety.msg.oldNewPsd.same": {zh: "新密码与旧密码相同！", en: "The new password and old password are same"},
	"safety.msg.oldPsd.wrong": {zh: "您输入的旧密码不正确！", en: "The old password is wrong"},
	"safety.msg.mobile.empty": {zh: "请输入手机号！", en: "Please enter the mobile number!"},
	"safety.msg.oldMobile.empty": {zh: "请输入旧手机！", en: "Please enter the old mobile number!"},
	"safety.msg.newMobile.empty": {zh: "请输入新手机！", en: "Please enter the new mobile number!"},
	"safety.msg.reNewMobile.empty": {zh: "请再次输入新手机！", en: "Please enter the renew mobile number!"},
	"safety.msg.mobile.error": {zh: "手机格式错误！", en: "The type of mobile number is error!"},
	"safety.msg.newMobile.error": {zh: "新手机格式错误！", en: "The type of new mobile number is error!"},
	"safety.msg.oldMobile.error": {zh: "旧手机格式错误！", en: "The type of old mobile number is error!"},
	"safety.msg.mobile.diff": {zh: "两次输入的手机不同！", en: "The mobile number you enter are different"},
	"safety.msg.mobile.exist": {zh: "手机已存在！", en: "The mobile is already exist"},
	"safety.msg.oldMobile.wrong": {zh: "旧手机不正确！", en: "The old mobile number is wrong!"},
	"safety.msg.oldEmail.empty": {zh: "请输入旧邮箱！", en: "Please enter the old mobile number!"},
	"safety.msg.newEmail.empty": {zh: "请输入新邮箱！", en: "Please enter the new mobile number!"},
	"safety.msg.password.short": {zh: "密码不能小于六位！", en: "The length of password can not be less than six!"},
	"safety.msg.reNewEmail.empty": {zh: "请再次输入新邮箱！", en: "Please enter the renew mobile number!"},
	"safety.msg.newEmail.error": {zh: "新邮箱格式错误！", en: "The type of new mobile number is error!"},
	"safety.msg.oldEmail.error": {zh: "旧邮箱格式错误！", en: "The type of old mobile number is error!"},
	"safety.msg.oldEmail.wrong": {zh: "旧邮箱不正确！", en: "The  old mobile number is wrong!"},
	"safety.msg.email.exist": {zh: "邮箱已存在！", en: "Email is already exist!"},
	"safety.msg.email.diff": {zh: "两次输入的邮箱不同！", en: "The mobile number you enter are different"},
	"safety.msg.noBindMobile":{zh:"请先绑定手机",en:"Please bind the mobile"},		
	"safety.msg.existMobile":{zh:"手机已存在",en:"mobileNum is already exist"},
	"safety.msg.userId.empty": {zh: "请选择用户Id！", en: "Please choose the userid!"},
	"safety.msg.exception": {zh: "系统访问异常！", en: "System access exception!"},
	"safety.msg.successfully": {zh: "修改成功！3秒后自动跳转。", en: "Saved successfully!It will jump back after three seconds."},
	"safety.msg.transAuth":{zh:"转移权限",en:"Transfer Authority"},		
	"safety.msg.confirmTrans":{zh:"确定转移权限吗？",en:"Do you comfirm to transfer authority"},
	"safety.msg.validateLoading": {zh: "正在验证您提交的信息，请稍后...", en: "Is verifying the information you submitted, please later..."},
	"safety.msg.password.simple": {zh: "密码不符合企业要求", en: "Password do not meet the requirements of the enterprise"}
}
